language: python
python:
  - "2.7"
  - "3.6"
  
# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install matplotlib
  - pip install pandas
  - pip install cython
  - pip install h5py==2.5.0
  - pip install git+https://github.com/ucberkeleyseti/blimpy
  - pip install git+https://github.com/kiyo-masui/bitshuffle
  - python setup.py install

# Command to run test
script: 
    - turboSETI voyager_test/Voyager1.single_coarse.fine_res.h5
    
branches:
  only:
    - master
